force-app/main/default/objects/Acitvity_Class__c/Acitvity_Class__c.object-meta.xml
<CustomObject>
    <label>Acitvity Class</label>
    <nameField>
        <displayFormat>ACN-{0000000000}</displayFormat>
        <label>Acitvity Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Acitvity_Class__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <externalId>true</externalId>
    <label>Class Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Acitvity_Class__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Activity Classes</relationshipLabel>
    <relationshipName>Activity_Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <displayFormat>FCT-{0000000000}</displayFormat>
        <label>Faculty ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty__c/fields/Faculty_Name__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Name__c</fullName>
    <externalId>true</externalId>
    <label>Faculty Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Major__c/Major__c.object-meta.xml
<CustomObject>
    <label>Major</label>
    <nameField>
        <displayFormat>MJR-{0000000000}</displayFormat>
        <label>Major ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Majors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Major__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Majors</relationshipLabel>
    <relationshipName>Majors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>RQS-{0000000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>Major__c</referenceTo>
    <relationshipLabel>Requests (Major)</relationshipLabel>
    <relationshipName>Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STD-{0000000000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Acitvity_Class__c.field-meta.xml
<CustomField>
    <fullName>Acitvity_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Acitvity Class</label>
    <referenceTo>Acitvity_Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Admission_Day__c.field-meta.xml
<CustomField>
    <fullName>Admission_Day__c</fullName>
    <label>Admission Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <formula>Acitvity_Class__r.Class_Name__c</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Faculty_Name__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Name__c</fullName>
    <formula>Faculty__r.Faculty_Name__c</formula>
    <label>Faculty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Free_Request_Remainder__c.field-meta.xml
<CustomField>
    <fullName>Free_Request_Remainder__c</fullName>
    <defaultValue>50</defaultValue>
    <label>Free Request Remainder</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>Major__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Card__c/Student_Card__c.object-meta.xml
<CustomObject>
    <label>Student Card</label>
    <nameField>
        <displayFormat>SCI-{0000000000}</displayFormat>
        <label>Student Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Card__c/fields/Admission_Year__c.field-meta.xml
<CustomField>
    <fullName>Admission_Year__c</fullName>
    <formula>TEXT( YEAR( Student__r.Admission_Day__c ))</formula>
    <label>Admission Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Card__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <formula>Student__r.Date_Of_Birth__c</formula>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student_Card__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <formula>Student__r.Faculty__r.Faculty_Name__c</formula>
    <label>Faculty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Card__c/fields/Id_Input__c.field-meta.xml
<CustomField>
    <fullName>Id_Input__c</fullName>
    <externalId>true</externalId>
    <label>Id Input</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Card__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Student Cards</relationshipLabel>
    <relationshipName>Student_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <displayFormat>SBJ-{0000000000}</displayFormat>
        <label>Subject ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>Faculty__c</referenceTo>
    <relationshipLabel>Subjects</relationshipLabel>
    <relationshipName>Subjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subject__c/fields/Faculty_Name__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Name__c</fullName>
    <formula>Faculty__r.Faculty_Name__c</formula>
    <label>Faculty Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subject__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <externalId>true</externalId>
    <label>Subject Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subject_Class__c/Subject_Class__c.object-meta.xml
<CustomObject>
    <label>Subject Class</label>
    <nameField>
        <displayFormat>SJC-{0000000000}</displayFormat>
        <label>Subject Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subject Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject_Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Subject Classes</relationshipLabel>
    <relationshipName>Subject_Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject_Class__c/fields/Subject_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Class_Name__c</fullName>
    <label>Subject Class Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subject_Class__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <formula>Subject__r.Subject_Name__c</formula>
    <label>Subject Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/Subject_Registration__c.object-meta.xml
<CustomObject>
    <label>Subject Registration</label>
    <nameField>
        <displayFormat>SRG-{0000000000}</displayFormat>
        <label>Subject Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subject Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject_Registration__c/fields/Final_Exam_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Exam_Score__c</fullName>
    <label>Final Exam Score</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Homework_Score__c.field-meta.xml
<CustomField>
    <fullName>Homework_Score__c</fullName>
    <label>Homework Score</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Mid_Term_Exam_Score__c.field-meta.xml
<CustomField>
    <fullName>Mid_Term_Exam_Score__c</fullName>
    <label>Mid-Term Exam Score</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Subject Registrations</relationshipLabel>
    <relationshipName>Subject_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Subject Registrations</relationshipLabel>
    <relationshipName>Subject_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Subject_Class__c.field-meta.xml
<CustomField>
    <fullName>Subject_Class__c</fullName>
    <label>Subject Class</label>
    <referenceTo>Subject_Class__c</referenceTo>
    <relationshipLabel>Subject Registrations</relationshipLabel>
    <relationshipName>Subject_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Subject_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Class_Name__c</fullName>
    <formula>Subject_Class__r.Subject_Class_Name__c</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subject_Registration__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <formula>Subject__r.Subject_Name__c</formula>
    <label>Subject</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Request_NewRequestController.cls
/**
 * @description       :
 * @author            : Tuan Tran
 * @group             :
 * @last modified on  : 12-13-2022
 * @last modified by  : Tuan Tran
 **/
public without sharing class Request_NewRequestController {
  @AuraEnabled
  public static Student__c getStudentInformation() {
    try {
      String userId = UserInfo.getUserId();
      System.debug('userId: ' + userId);
      Student__c student = [
        SELECT
          Id,
          Name,
          Student_Name__c,
          Date_Of_Birth__c,
          Acitvity_Class__r.Class_Name__c,
          Faculty__r.Faculty_Name__c,
          Free_Request_Remainder__c,
          Major__c,
          Admission_Day__c,
          (
            SELECT Id, Name, Admission_Year__c, Id_Input__c, Is_Valid__c
            FROM Student_Cards__r
          )
        FROM Student__c
        WHERE User__c = :userId
      ];
      return student;
    } catch (Exception e) {
      System.debug('Fail to get Student Information: ' + e.getMessage());
      return null;
    }
  }
  @AuraEnabled
  public static Student__c getStudentInformationWId(String requestId) {
    try {
      Request__c req = [SELECT Id, Student__c FROM Request__c WHERE Id = :requestId];
      Student__c student = [
        SELECT
          Id,
          Name,
          Student_Name__c,
          Date_Of_Birth__c,
          Acitvity_Class__r.Class_Name__c,
          Faculty__r.Faculty_Name__c,
          Free_Request_Remainder__c,
          Major__c,
          Admission_Day__c,
          (
            SELECT Id, Name, Admission_Year__c, Id_Input__c, Is_Valid__c
            FROM Student_Cards__r
          )
        FROM Student__c
        WHERE Id = :req.Student__c
      ];
      return student;
    } catch (Exception e) {
      System.debug('Fail to get Student Information: ' + e.getMessage());
      return null;
    }
  }
  @AuraEnabled
  public static String getSemesterTranscript(String studentId, Decimal term) {
    try {
      List<SubjectRegistration> lsSubjectRegistrationResponse = new List<SubjectRegistration>();
      List<Subject_Registration__c> lsSubjectRegistration = [
        SELECT
          Id,
          Subject__r.Subject_Name__c,
          Subject_Class__r.Subject_Class_Name__c,
          Homework_Score__c,
          Mid_Term_Exam_Score__c,
          Final_Exam_Score__c,
          Overall_Score__c
        FROM Subject_Registration__c
        WHERE Student__c = :studentId AND Semester__c = :String.valueOf(term)
      ];
      System.debug('lsSubjectRegistration: ' + lsSubjectRegistration);
      for (Subject_Registration__c sr : lsSubjectRegistration) {
        SubjectRegistration srRes = new SubjectRegistration();
        srRes.id = sr.Id;
        srRes.studentId = studentId;
        srRes.term = term;
        srRes.subjectName = sr.Subject__r.Subject_Name__c;
        srRes.className = sr.Subject_Class__r.Subject_Class_Name__c;
        srRes.homeworkScore = sr.Homework_Score__c;
        srRes.midTermScore = sr.Mid_Term_Exam_Score__c;
        srRes.finalExamScore = sr.Final_Exam_Score__c;
        srRes.overallScore = sr.Overall_Score__c;
        lsSubjectRegistrationResponse.add(srRes);
      }
      System.debug(
        'lsSubjectRegistrationResponse: ' + lsSubjectRegistrationResponse
      );

      return JSON.serialize(lsSubjectRegistrationResponse);
    } catch (Exception e) {
      System.debug('Fail to get semester transcript: ' + e.getMessage());
      return null;
    }
  }
  @AuraEnabled
  public static string getYearTranscript(
    String studentId,
    String admissionYear
  ) {
    try {
      List<String> lsTerms = getLsTermsForCurrentTime(admissionYear);
      return null;
    } catch (Exception e) {
      System.debug('Fail to get Year Transcript. Error: ' + e.getMessage());
      return null;
    }
  }
  public static List<String> getLsTermsForCurrentTime(String admissionYear) {
    Integer currentYear = System.today().year();
    Integer currentMonth = System.today().month();
    Integer yearNumber;
    List<String> lsTerm = new List<String>();
    if (currentMonth <= 7 && currentMonth > 5) {
      yearNumber = currentYear - Integer.valueOf(admissionYear);
      lsTerm.add(String.valueOf(yearNumber * 2 - 1));
      lsTerm.add(String.valueOf(yearNumber * 2));
      lsTerm.add(String.valueOf(yearNumber * 2 + 0.5));
    } else if (currentMonth < 5) {
      yearNumber = currentYear - Integer.valueOf(admissionYear);
      lsTerm.add(String.valueOf(yearNumber * 2 - 1));
      lsTerm.add(String.valueOf(yearNumber * 2));
    }
    return lsTerm;
  }
  public class SubjectRegistration {
    public String id;
    public String studentId;
    public Double term;
    public String subjectName;
    public String className;
    public Double homeworkScore;
    public Double midTermScore;
    public Double finalExamScore;
    public Double overallScore;
  }
}